# Generated by Django 3.2.23 on 2024-02-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20240204_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
