# Generated by Django 3.2.23 on 2024-02-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_scrape_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='worksheet_file',
            field=models.FileField(blank=True, null=True, upload_to='worksheet_files/'),
        ),
    ]
